/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.ConexaoBD;
import Classes.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angélica
 */
public class FormGerenciarUsuario extends javax.swing.JFrame {
    
    Usuario usuarioForm;
    
    private String nomeUsuario;

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
      
    /**
     * Creates new form FormGerenUsuario
     */
    public FormGerenciarUsuario() {
           
        initComponents();
        usuarioForm = new Usuario();
        Vector listaUsuarios = usuarioForm.recuperarListaUsuarios();
        
        Vector colunas = new Vector<>();
   
        colunas.add("id");
        colunas.add("nome_completo");
        colunas.add("email");
        colunas.add("telefone");
        colunas.add("nome_usuario");
        colunas.add("senha");
               
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(listaUsuarios, colunas);
        
        tblUsuarios.setModel(dataModel);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btCadastrarUsuario = new javax.swing.JButton();
        btVoltarTelaInicial = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btnAtualizarTabelaUsuario = new javax.swing.JButton();
        txtUsuarioAtual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome_completo", "email", "telefone", "nome_usuario", "senha"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jScrollPane2.setViewportView(jScrollPane1);

        btCadastrarUsuario.setText("Cadastrar Novo Usuario");
        btCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarUsuarioActionPerformed(evt);
            }
        });

        btVoltarTelaInicial.setText("Voltar");
        btVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaInicialActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lbTitulo.setText("Gerenciar Usuários");

        btnAtualizarTabelaUsuario.setText("Atualizar");
        btnAtualizarTabelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaUsuarioActionPerformed(evt);
            }
        });

        txtUsuarioAtual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuarioAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAtualActionPerformed(evt);
            }
        });
        txtUsuarioAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioAtualKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btVoltarTelaInicial)
                        .addGap(54, 54, 54)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnAtualizarTabelaUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCadastrarUsuario)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCadastrarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarTelaInicial)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluirUsuario)
                    .addComponent(btnAtualizarTabelaUsuario))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarUsuarioActionPerformed
        FormCadastroUsuario telaCadastroUsuario = new FormCadastroUsuario();
        
        telaCadastroUsuario.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_btCadastrarUsuarioActionPerformed

    private void btVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaInicialActionPerformed

        FormTelaInicial telaInicial = new FormTelaInicial();
        
        telaInicial.setNomeUsuario(nomeUsuario);
        telaInicial.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_btVoltarTelaInicialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        FormEditarUsuario telaEditar = new FormEditarUsuario();
                    
        if (tblUsuarios.getSelectedRow() != -1){
            
            Usuario usuario = new Usuario();


            usuario.setId((int)tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0));


            usuario.deletarUsuario(usuario);
            usuario.recuperarListaUsuarios();
            
        } else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }
        
        telaEditar.setVisible(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
            
        if (tblUsuarios.getSelectedRow() != -1){
            
            Usuario usuario = new Usuario();


            usuario.setId((int)tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0));


            usuario.deletarUsuario(usuario);
            usuario.recuperarListaUsuarios();
            
        } else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnAtualizarTabelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaUsuarioActionPerformed
        
        usuarioForm = new Usuario();
        Vector listaUsuarios = usuarioForm.recuperarListaUsuarios();
        
        Vector colunas = new Vector<>();
   
        colunas.add("id");
        colunas.add("nome_completo");
        colunas.add("email");
        colunas.add("telefone");
        colunas.add("nome_usuario");
        colunas.add("senha");
               
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(listaUsuarios, colunas);
        
        tblUsuarios.setModel(dataModel);
 
        
        
    }//GEN-LAST:event_btnAtualizarTabelaUsuarioActionPerformed

    private void txtUsuarioAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAtualActionPerformed

    private void txtUsuarioAtualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioAtualKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAtualKeyReleased

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        if(tblUsuarios.getSelectedRow() != -1){

            txtUsuarioAtual.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 1).toString());
            
        }        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGerenciarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarUsuario;
    private javax.swing.JButton btVoltarTelaInicial;
    private javax.swing.JButton btnAtualizarTabelaUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtUsuarioAtual;
    // End of variables declaration//GEN-END:variables
}
